@startuml Immatricolazione Estera

actor Studente

participant "Università ospitante" as UniOspitante
participant "BlockChain Ethereum" as Blockchain

group Immatricolazione presso università ospitante

   Studente -> UniOspitante : Invio credenziale studente dell'università di origine\ncon almeno la property "subjectInfo"
   UniOspitante -> Blockchain : Verifica della validità della credenziale attraverso il suo CID
   Blockchain --> UniOspitante : Esito verifica
   UniOspitante -> Blockchain : Richiesta della chiave pubblica associata al UID ricevuto
   Blockchain --> UniOspitante : Chiave pubblica università di origine
   UniOspitante -> UniOspitante : Verifica della firma presente nella credenziale
   UniOspitante -> Blockchain : Richiesta della chiave pubblica associata al SID ricevuto
   Blockchain --> UniOspitante : Chiave pubblica studente

   group Procedura di autenticazione

      UniOspitante -> Studente : Challenge per verifica autenticità mittente
      Studente --> UniOspitante : Challenge firmata
      UniOspitante -> UniOspitante : Verifica della firma

   end

UniOspitante --> UniOspitante : Salvataggio credenziale studente per future interazioni.
UniOspitante --> Studente : Conferma di inizio erasmus

end

@enduml
